[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = "o0g9o3ve1qe2"
  CONTENTFUL_ACCESS_TOKEN = "EAlbgPP0y83ZA6bal8h9XbPqmMONbMuCEhNqvH19iL4"
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = "iD2QTtfecwtSDqGfmqgGpAm7Ea1OtyF9USmsfmWkzZY"
